[project]
name = "to-do"
version = "0.1.0"
description = "Command-line Todo application with in-memory storage for Phase I of the Evolution of Todo project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "black>=25.12.0",
    "flake8>=7.3.0",
    "mypy>=1.19.1",
    "pytest>=9.0.2",
]
